schematics = {
"Tier 2": [
    {"inputs":[[40,"Biofuels"],[40,"Precious Metals"]],"output":[5,"Biocells"]},
    {"inputs":[[40,"Reactive Metals"],[40,"Toxic Metals"]],"output":[5,"Construction Blocks"]},
    {"inputs":[[40,"Toxic Metals"],[40,"Chiral Structures"]],"output":[5,"Consumer Electronics"]},
    {"inputs":[[40,"Electrolytes"],[40,"Water"]],"output":[5,"Coolant"]},
    {"inputs":[[40,"Precious Metals"],[40,"Toxic Metals"]],"output":[5,"Enriched Uranium"]},
    {"inputs":[[40,"Bacteria"],[40,"Proteins"]],"output":[5,"Fertilizer"]},
    {"inputs":[[40,"Proteins"],[40,"Biomass"]],"output":[5,"Genetically Enhanced Livestock"]},
    {"inputs":[[40,"Proteins"],[40,"Biofuels"]],"output":[5,"Livestock"]},
    {"inputs":[[40,"Reactive Metals"],[40,"Precious Metals"]],"output":[5,"Mechanical Parts"]},
    {"inputs":[[40,"Industrial Fibers"],[40,"Silicon"]],"output":[5,"Microfiber Shielding"]},
    {"inputs":[[40,"Chiral Structures"],[40,"Silicon"]],"output":[5,"Miniature Electronics"]},
    {"inputs":[[40,"Bacteria"],[40,"Reactive Metals"]],"output":[5,"Nanites"]},
    {"inputs":[[40,"Oxidizing Compound"],[40,"Oxygen"]],"output":[5,"Oxides"]},
    {"inputs":[[40,"Oxidizing Compound"],[40,"Industrial Fibers"]],"output":[5,"Polyaramids"]},
    {"inputs":[[40,"Biofuels"],[40,"Industrial Fibers"]],"output":[5,"Polytextiles"]},
    {"inputs":[[40,"Plasmoids"],[40,"Electrolytes"]],"output":[5,"Rocket Fuel"]},
    {"inputs":[[40,"Oxidizing Compound"],[40,"Silicon"]],"output":[5,"Silicate Glass"]},
    {"inputs":[[40,"Plasmoids"],[40,"Water"]],"output":[5,"Superconductors"]},
    {"inputs":[[40,"Oxygen"],[40,"Biomass"]],"output":[5,"Supertensile Plastics"]},
    {"inputs":[[40,"Electrolytes"],[40,"Oxygen"]],"output":[5,"Synthetic Oil"]},
    {"inputs":[[40,"Bacteria"],[40,"Water"]],"output":[5,"Test Cultures"]},
    {"inputs":[[40,"Plasmoids"],[40,"Chiral Structures"]],"output":[5,"Transmitter"]},
    {"inputs":[[40,"Bacteria"],[40,"Biomass"]],"output":[5,"Viral Agent"]},
    {"inputs":[[40,"Reactive Metals"],[40,"Water"]],"output":[5,"Water-Cooled CPU"]},
    ],
"Tier 3": [
    {"inputs":[[10,"Nanites"],[10,"Livestock"],[10,"Construction Blocks"]],"output":[3,"Biotech Research Reports"]},
    {"inputs":[[10,"Silicate Glass"],[10,"Rocket Fuel"]],"output":[3,"Camera Drones"]},
    {"inputs":[[10,"Oxides"],[10,"Coolant"]],"output":[3,"Condensates"]},
    {"inputs":[[10,"Test Cultures"],[10,"Synthetic Oil"],[10,"Fertilizer"]],"output":[3,"Cryoprotectant Solution"]},
    {"inputs":[[10,"Supertensile Plastics"],[10,"Microfiber Shielding"]],"output":[3,"Data Chips"]},
    {"inputs":[[10,"Oxides"],[10,"Biocells"],[10,"Superconductors"]],"output":[3,"Gel-Matrix Biopaste"]},
    {"inputs":[[10,"Water-Cooled CPU"],[10,"Transmitter"]],"output":[3,"Guidance Systems"]},
    {"inputs":[[10,"Polytextiles"],[10,"Viral Agent"],[10,"Transmitter"]],"output":[3,"Hazmat Detection Systems"]},
    {"inputs":[[10,"Polyaramids"],[10,"Genetically Enhanced Livestock"]],"output":[3,"Hermetic Membranes"]},
    {"inputs":[[10,"Polyaramids"],[10,"Transmitter"]],"output":[3,"High-Tech Transmitters"]},
    {"inputs":[[10,"Fertilizer"],[10,"Polytextiles"]],"output":[3,"Industrial Explosives"]},
    {"inputs":[[10,"Biocells"],[10,"Silicate Glass"]],"output":[3,"Neocoms"]},
    {"inputs":[[10,"Enriched Uranium"],[10,"Microfiber Shielding"]],"output":[3,"Nuclear Reactors"]},
    {"inputs":[[10,"Supertensile Plastics"],[10,"Mechanical Parts"],[10,"Miniature Electronics"]],"output":[3,"Planetary Vehicles"]},
    {"inputs":[[10,"Mechanical Parts"],[10,"Consumer Electronics"]],"output":[3,"Robotics"]},
    {"inputs":[[10,"Construction Blocks"],[10,"Miniature Electronics"]],"output":[3,"Smartfab Units"]},
    {"inputs":[[10,"Water-Cooled CPU"],[10,"Coolant"],[10,"Consumer Electronics"]],"output":[3,"Supercomputers"]},
    {"inputs":[[10,"Supertensile Plastics"],[10,"Test Cultures"]],"output":[3,"Synthetic Synapses"]},
    {"inputs":[[10,"Biocells"],[10,"Nanites"]],"output":[3,"Transcranial Microcontrollers"]},
    {"inputs":[[10,"Synthetic Oil"],[10,"Superconductors"]],"output":[3,"Ukomi Superconductors"]},
    {"inputs":[[10,"Livestock"],[10,"Viral Agent"]],"output":[3,"Vaccines"]},
    ],
"Tier 4": [
    {"inputs":[[6,"Neocoms"],[6,"Data Chips"],[6,"High-Tech Transmitters"]],"output":[1,"Broadcast Node"]},
    {"inputs":[[6,"Gel-Matrix Biopaste"],[6,"Hazmat Detection Systems"],[6,"Planetary Vehicles"]],"output":[1,"Integrity Response Drones"]},
    {"inputs":[[6,"Industrial Explosives"],[40,"Reactive Metals"],[6,"Ukomi Superconductors"]],"output":[1,"Nano-Factory"]},
    {"inputs":[[6,"Condensates"],[40,"Bacteria"],[6,"Robotics"]],"output":[1,"Organic Mortar Applicators"]},
    {"inputs":[[6,"Synthetic Synapses"],[6,"Guidance Systems"],[6,"Transcranial Microcontrollers"]],"output":[1,"Recursive Computing Module"]},
    {"inputs":[[6,"Camera Drones"],[6,"Nuclear Reactors"],[6,"Hermetic Membranes"]],"output":[1,"Self-Harmonizing Power Core"]},
    {"inputs":[[6,"Smartfab Units"],[40,"Water"],[6,"Vaccines"]],"output":[1,"Sterile Conduits"]},
    {"inputs":[[6,"Supercomputers"],[6,"Biotech Research Reports"],[6,"Cryoprotectant Solution"]],"output":[1,"Wetware Mainframe"]},
    ],
}
tiers = list(sorted(schematics.keys()))
